name: build
on:
  - push
  - pull_request
jobs:
  build:
    runs-on:
      - ubuntu-latest
      - windows-latest
    strategy:
      matrix:
        go: [ '1.11.x', '1.12.x', '1.13.x' ]
    name: Go ${{ matrix.go }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test
