name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.11.13', '1.12.14', '1.13.5' ]
    name: Go ${{ matrix.go }} build
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test
